In [1]:
# Write a Python program to implement logistic Regression. Use dataset crash.csv is an 
# accident survivor’s dataset portal for USA hosted by data.gov. The dataset contains 
# passengers age and speed of vehicle (mph) at the time of impact and fate of passengers 
# (1 for survived and 0 for not survived) after a crash. Use logistic regression to decide if 
# the age and speed can predict the survivability of the passengers.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv("D:/Machin Learning/ML/ML Preactical Slips/dataset/crash.csv")
data

   age   speed  fate
0    25    110     1
1    26    150     0
2    30    160     0
3    32    100     1
4    40    140     0
5    41     90     1
6    45     90     1
7    46     87     1

In [4]:
data.dropna()

   age   speed  fate
0    25    110     1
1    26    150     0
2    30    160     0
3    32    100     1
4    40    140     0
5    41     90     1
6    45     90     1
7    46     87     1

In [23]:
X = data[["age", "speed" , "fate"]]

KeyError: "['age'] not in index"